// Generated by Wrangler by running `wrangler types`

interface Env {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_D1_DATABASE_ID: string;
	CLOUDFLARE_D1_DATABASE_ID_STAGING: string;
	CLOUDFLARE_D1_TOKEN: string;
	DB: D1Database;
	NOTIFY_WORKFLOW: Workflow;
}
